/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciogui;

/**
 *
 * @author Estudiante
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);//Centra la ventana
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnOpciones = new javax.swing.JMenu();
        btnCheckBox = new javax.swing.JMenuItem();
        btnRadioButton = new javax.swing.JMenuItem();
        btntextfield = new javax.swing.JMenuItem();
        btntextfield2 = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOpciones.setText("opciones");
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });

        btnCheckBox.setText("Check Box");
        btnCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBoxActionPerformed(evt);
            }
        });
        btnOpciones.add(btnCheckBox);

        btnRadioButton.setText("Radio Button");
        btnRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioButtonActionPerformed(evt);
            }
        });
        btnOpciones.add(btnRadioButton);

        btntextfield.setText("TextField");
        btntextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntextfieldActionPerformed(evt);
            }
        });
        btnOpciones.add(btntextfield);

        btntextfield2.setText("TextField2");
        btntextfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntextfield2ActionPerformed(evt);
            }
        });
        btnOpciones.add(btntextfield2);

        jMenuBar1.add(btnOpciones);

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckBoxActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        CheckBox ventanaSecundaria = new CheckBox(this,true);
        ventanaSecundaria.pack();
        ventanaSecundaria.setVisible(true);
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void btnRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioButtonActionPerformed
        // TODO add your handling code here:
        radioButton ventanaSecundaria = new radioButton(this,true);
        ventanaSecundaria.pack();
        ventanaSecundaria.setVisible(true);
    }//GEN-LAST:event_btnRadioButtonActionPerformed

    private void btntextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntextfieldActionPerformed
        // TODO add your handling code here:
        textField ventanaSecundaria = new  textField (this,true);
    ventanaSecundaria.pack();
    ventanaSecundaria.setVisible(true);
    }//GEN-LAST:event_btntextfieldActionPerformed

    private void btntextfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntextfield2ActionPerformed
        // TODO add your handling code here:
        textfield2 ventanaSecundaria = new textfield2(this,true);
        ventanaSecundaria.pack();
        ventanaSecundaria.setVisible(true);
    }//GEN-LAST:event_btntextfield2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCheckBox;
    private javax.swing.JMenu btnOpciones;
    private javax.swing.JMenuItem btnRadioButton;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JMenuItem btntextfield;
    private javax.swing.JMenuItem btntextfield2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
